"""Shared MR/PR command argument builders."""

import logging
from typing import TYPE_CHECKING, Any, List

from .validation import validate_issue_description

if TYPE_CHECKING:
    from ..config import Config

logger = logging.getLogger(__name__)


def validate_mr_args(args: Any, config: "Config") -> None:
    """Validate MR/PR title and description against template requirements.

    Skips all validation when --fill is set because title and description are
    generated by the platform CLI at subprocess time and are not available for
    inspection beforehand.

    Args:
        args: Parsed CLI arguments.
        config: Project configuration.

    Raises:
        ValueError: If title is absent (without --fill), or if description is
            absent (without --fill), or if description is missing required sections.
    """
    logger.debug(
        "Validating MR args: title=%r has_description=%s fill=%s",
        getattr(args, "title", None),
        bool(getattr(args, "description", None)),
        bool(getattr(args, "fill", False)),
    )

    fill = getattr(args, "fill", False)
    if fill:
        # Title and description will be generated by the platform CLI at runtime.
        # Nothing to validate here.
        return

    if not getattr(args, "title", None):
        raise ValueError("MR title is required (use --title or --fill)")

    description = getattr(args, "description", None)
    if not description:
        raise ValueError("MR description is required (use --description or --fill)")

    validate_issue_description(
        description=description,
        required_sections=config.get_required_mr_sections(),
        issue_title=args.title,
        entity_type="MR",
    )

    required_fields = config.get_required_mr_fields()
    logger.debug(
        "MR '%s': required_fields=%s reviewer_count=%d label_count=%d",
        getattr(args, "title", None),
        required_fields,
        len(getattr(args, "reviewer", None) or []),
        len(getattr(args, "label", None) or []),
    )

    if "reviewers" in required_fields:
        if not (getattr(args, "reviewer", None) or []):
            raise ValueError(
                "MR requires at least one reviewer. "
                "Pass --reviewer USERNAME, or remove 'reviewers' from "
                "mr_template.required_fields in your config."
            )

    if "labels" in required_fields:
        if not (getattr(args, "label", None) or []):
            raise ValueError(
                "MR requires at least one label. "
                "Pass --label LABEL, or remove 'labels' from "
                "mr_template.required_fields in your config."
            )

    if required_fields:
        logger.info(
            "MR '%s': required fields validated: %s",
            getattr(args, "title", None),
            required_fields,
        )


def append_common_mr_flags(cmd: List[str], args: Any) -> None:
    """Append shared assignee/reviewer/label/milestone flags to a command list.

    Used by both the GitLab (glab mr create) and GitHub (gh pr create) handlers
    to avoid duplicating flag-building logic.  Target-branch flag is intentionally
    excluded because the two CLIs use different flag names (--target-branch vs
    --base).

    Args:
        cmd: Mutable command list to extend in-place.
        args: Parsed CLI arguments; expected to expose ``assignee``, ``reviewer``,
              ``label``, and ``milestone`` attributes.
    """
    for assignee in args.assignee or []:
        cmd.extend(["--assignee", assignee])

    for reviewer in args.reviewer or []:
        cmd.extend(["--reviewer", reviewer])

    for label in args.label or []:
        cmd.extend(["--label", label])

    if args.milestone:
        cmd.extend(["--milestone", args.milestone])
